### ISSUE TITLE
allow te_check to accept a list of parks

### ISSUE THREAD

**Issue by RobLBaker** [nationalparkservice/QCkit#28]
Currently you can only do 1 park at a time and the Odata API pulls all the species from that park as well as all the species from all parks. This should be separated out so that it pulls the species from all parks just once and then pulls the species from the list of specified parks, rbinds them.

The question is, @juddpatterson should it then remove duplicate species? It is likely that nearby parks (for instance in the same network or ecoregion) share threatened and endangered species. Should the ouput include which parks the species is listed in/for? Or is that too much information?

**Comment by juddpatterson** [comment]
I haven't messed with the Odata syntax much either, but I know it accepts multiple requests (e.g. where ParkCode = All, BISC, or EVER, which could keep it all in a single Odata call too:

https://irmadev.nps.gov/PrototypeCSVtoAPI/odata/FederalConservationListTaxaforDataProtection2272462?$filter=ParkCode%20eq%20%27EVER%27%20or%20ParkCode%20eq%20%27All%27or%20ParkCode%20eq%20%27BISC%27

My initial reaction is that since the original data includes a ParkCode field, we should retain that in the output too (rather than removing and collapsing to non-duplicates). I'm thinking of a multipark dataset where you feed the te_check a list of scientific names and tell it to check across a couple parks. I think you'd want to see the ParkCodes as the end to better interpret the "hits".
