### ISSUE TITLE
DRR table footnote superscripts can be confusing

### ISSUE THREAD

**Issue by RobLBaker** [nationalparkservice/QCkit#92]
Add a space between the superscripts and subsequent text in the "notes" portion below each table in the DRR Template.

**Comment by sarahkelso** [comment]
This issue is similar to three that I found:
1) Is there a way to organize the table notes to include less information for each individual table? For example, have a paragraph before or after the tables that summarizes any necessary information and links to the superscripts. 
2) For table 3 and 4 this description of the calculation is confusing: % Accepted is calculated as the number of accepted (where A and AE are both considered accepted) divided by the total number of observations plus the number of missing observations.
- the total number of observations includes the missing data, so I'm not sure why it would be added into the total again
3) For table 3 and 4 this note isn't necessarily true: All non-missing data in specified unflagged columns are considered accepted. 
- What happens if a coordinate pair is present but determined to be wrong and therefore rejected?

**Comment by RobLBaker** [comment]
1. I'm not sure if there is a good way to put links from within the document to other locations in the document. It's worth discussing with the publications team, but not worth pursuing until we know it will work with their workflow. 
2.  In theory there should not be any missing values for data flagging columns as there is no accepted missing value code for those columns, but I'll look into what happened here. I know there was a lot of back on forth on how to handle this.
3. Yes, I think there is a typo there. Perhaps it should read, "All non-missing data in unflagged columns are considered accepted".
